# seprate the data and create a table
colnames(treesgrowth)<-c("site","treeID","circum-2004","circum-2009",""circum-2014",""circum-2019")
View(treesgrowth)
treesgrowth<-read.table("growth_data.csv")
head(treesgrowth)
treesgrowth<-read.table("growth_data.csv",sep = ",")
head(treesgrowth)
str(treesgrowth)
treesgrowth<-read.table("growth_data.csv",sep = ",",header = TRUE)
str(treesgrowth)
treegrowth <- read.csv("data/growth_data.csv", header = TRUE, stringsAsFactors = FALSE)
treegrowth <- read.csv("data/growth_data.csv", header = TRUE, stringsAsFactors = FALSE)
head(treesgrowth)
str(treesgrowth)
colnames(treesgrowth)<-c("site","treeID","circum-2004","circum-2009",""circum-2014",""circum-2019")
head(treesgrowth)
str(treesgrowth)
treegrowth <- read.csv("growth_data.csv", header = TRUE, stringsAsFactors = FALSE)
head(treesgrowth)
str(treesgrowth)
treegrowth <- read.csv("growth_data.csv", header = TRUE, stringsAsFactors = FALSE)
treegrowth <- read.csv("growth_data.csv", header = TRUE, stringsAsFactors = FALSE)
head(treesgrowth)
treesgrowth <- read.csv("growth_data.csv", header = TRUE, stringsAsFactors = FALSE)
head(treesgrowth)
str(treesgrowth)