# subset the sepate the two sites
colnames(treesgrowth)
ne<- subset(treesgrowth,site="northeast")
subset.data.frame(northeast)
head(ne)
tail(ne)
ne <- subset(treesgrowth,Site="northeast")
head(ne)
tail(ne)
ne <- subset(treesgrowth,Site="northeast")
head(ne)
tail(ne)
str(ne)
ne<- subset(treesgrowth,Site =="northeast")
head(ne)
tail(ne)
str(ne)
#get the men of the and SD of northeast
mean(ne$Circumf_2004_cm)
mean(ne$Circumf_2019_cm)
sd(ne$Circumf_2004_cm)
sd(ne$Circumf_2019_cm)
# get the mean and Sd of the southwest
sw<-subset(treesgrowth,Site =="southwest")
head(sw)
head(sw)
str(ne)
mean(sw$Circumf_2004_cm)
mean(sw$Circumf_2019_cm)
sd(sw$Circumf_2004_cm)
sd(sw$Circumf_2019_cm)